In [ ]:
import numpy as np

In [ ]:
mylist=[1,2,3]

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
mylist=([1,2,3],[3,4,5
                 ])

In [ ]:
np.array(mylist)


array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
a=np.zeros(4)
a=a.astype(int)

In [ ]:
print (a)

[0 0 0 0]


In [ ]:
np.zeros((4,4
          )).astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones(4)


array([1., 1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(2,5,20)

array([2.        , 2.15789474, 2.31578947, 2.47368421, 2.63157895,
       2.78947368, 2.94736842, 3.10526316, 3.26315789, 3.42105263,
       3.57894737, 3.73684211, 3.89473684, 4.05263158, 4.21052632,
       4.36842105, 4.52631579, 4.68421053, 4.84210526, 5.        ])

In [ ]:
np.random.randn(5)

array([-1.77198069,  0.63525739,  0.08089612,  0.90437172, -0.83304658])

In [ ]:
np.random.randint(1,100)

3

In [ ]:
np.random.randint(1,100,10)

array([88, 67, 13, 44, 52, 67, 24, 86, 90, 87])

In [ ]:
arr=np.random.randint(1,100,10)

In [ ]:
arr

array([67, 15,  8, 54, 71, 36, 97, 58, 77, 31])

In [ ]:
arr.shape

(10,)

In [ ]:
arr.reshape(5,2)

array([[67, 15],
       [ 8, 54],
       [71, 36],
       [97, 58],
       [77, 31]])

In [ ]:
arr.max()

97

In [ ]:
arr.min()

8

In [ ]:
arr.argmax()

6

In [ ]:
arr.argmin()

2

In [ ]:
arr=np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr[:3]

array([0, 1, 2])

In [ ]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [ ]:
arr=np.array([[32,30,31],[40,41,42],[50,51,52]])

In [ ]:
arr

array([[32, 30, 31],
       [40, 41, 42],
       [50, 51, 52]])

In [ ]:
arr[2:,0]

array([50])

In [ ]:
arr[2:,2]

array([52])

In [ ]:
arr[2][1]

51

In [ ]:
arr[:2,2]

array([31, 42])

In [ ]:
arr[:2,1:]

array([[30, 31],
       [41, 42]])

In [ ]:
arr[1:,1:]

array([[41, 42],
       [51, 52]])

In [ ]:
arr[1:,:2]

array([[40, 41],
       [50, 51]])

In [ ]:
arr=np.arange(1,8)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr[arr>4]

array([5, 6, 7])